Layout/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 30
Style/NumericLiterals:
  Enabled: false
Metrics/AbcSize:
  Max: 55
Metrics/ClassLength:
  Max: 200
Metrics/PerceivedComplexity:
  Max: 12
Metrics/CyclomaticComplexity:
  Max: 12
AllCops:
  NewCops: enable
  TargetRubyVersion: 2.4
