Layout/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 30
Style/NumericLiterals:
  Enabled: false
Metrics/AbcSize:
  Max: 50
Metrics/ClassLength:
  Max: 200
Metrics/PerceivedComplexity:
  Max: 12
Metrics/CyclomaticComplexity:
  Max: 10
