Layout/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 30
Style/NumericLiterals:
  Enabled: false
Metrics/AbcSize:
  Max: 55
Metrics/ClassLength:
  Max: 200
Metrics/PerceivedComplexity:
  Max: 16
Metrics/CyclomaticComplexity:
  Max: 16
AllCops:
  NewCops: enable
  TargetRubyVersion: 2.4
