name: 'Build site'
description: 'Build an IRIS-HEP style website. INDICO keys should be set, and rake should be supported.'
runs:
  using: composite
  steps:
  - name: Restore bundle cache
    uses: actions/cache@v2
    with:
      path: vendor/bundle
      key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
      restore-keys: |
        ${{ runner.os }}-gems-

  - name: Restore publication cache
    uses: actions/cache@v2
    with:
      path: _cache
      key: ${{ runner.os }}-_cache-${{ hashFiles('_data/publications/*.yml') }}

  - uses: ruby/setup-ruby@v1
    with:
      ruby-version: '3.1'

  - name: Install apt requirements
    shell: bash
    run: |
      sudo apt-get update
      sudo apt-get install libxslt-dev libxml2-dev
      gem install bundler

  - name: Bundle install
    shell: bash
    run: |
      bundle config path vendor/bundle
      bundle install --jobs 4 --retry 3
    env:
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true

