open: yes
postdate:
title: Securing container images for infrastructure services
description: >
  The Open Science Grid (OSG) offers an integrated software stack used by the
  High-Energy Physics community to meet their computing needs. As container images
  and orchestration technologies grow in popularity, the OSG has started to
  distribute images through the Harbor container registry. We seek a fellow who
  will investigate image vulnerability scanning tools and configurations to
  improve the security posture of our images.
contacts:
  - brianhlin
  - matyasselmeci
