inspire-id: 2708713
title: "Training and Onboarding initiatives in High Energy Physics experiments"
link: https://arxiv.org/abs/2310.07342
date: 2023-10-23
citation: "S. Hageboeck, A. Reinsvold Hall, N. Skidmore, G. A. Stewart, G. Benelli, B. Carlson, C. David, J. Davies, W. Deconinck, D. DeMuth Jr., P. Elmer, R. B. Garg, K. Lieret, V. Lukashenko, S. Malik, A. Morris, H. Schellman, J. Veatch, M. Hernandez Villanueva"
focus-area: ssc
submitted-to: Presented at CHEP2023
project:
